### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by ubongashorts** [ryan-hami/Mp4-To-CCC#1]
awesome work, i'd like to ask a few questions:

1. if i want the ascii captions to fill an entire 1920 x 1080 video how many colums should i put?

2. how can i change the size of the ascii so that the resolution of the mp4 is higher quality

3. how can i reduce the size so it does not lag the video

4. do u have discord?

Thanks!

**Comment by ubongashorts** [comment]
Youtube is not letting me upload any .ytt file larger than 8kb does anyone know a way to be able to upload larger files? It would greatly help me!

**Comment by ryan-hami** [comment]
1./2. You can change caption font size in video settings under "Subtitles/CC" then "Options"
Not sure the exact number of columns you're gonna want, but should be a fairly quick experiment on your part.
![image](https://github.com/user-attachments/assets/7cd68292-d83d-4dd6-ae68-a4a4a47edd9d)

3. Less frames or avoid using the .ytt file format. If you can live without color, .srt is the way to go.
4. @rtab

**Comment by ubongashorts** [comment]
Thank you for the response! i just sent u a friend request :D
